export enum PaymentStatus {
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_NOT_REQUIRED = 'PAYMENT_NOT_REQUIRED',
  PAYMENT_FULL = 'PAYMENT_FULL',
  PAYMENT_PARTIAL = 'PAYMENT_PARTIAL',
}
